openapi: 3.0.0
components:
  responses:
    CompaniesResponse:
      description: A JSON array of companies names
      content:
        application/json:
          schema: 
            type: array
            items: 
              type: string