openapi: 3.0.0
components:
  requestBodies:
    UsersRequest:
      content:
        'application/x-www-form-urlencoded':
          schema:
            properties:
                name:
                  description: Updated name of the user
                  type: string
                status:
                  description: Updated status of the user
                  type: string
            required:
              - status
  responses:
    CompaniesResponse:
      description: A JSON array of companies names
      content:
        application/json:
          schema: 
            type: array
            items: 
              type: string
    CompaniesErrorResponse:
      description: An error response when trying to resolve companies
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExtendedErrorModel'
    ShopsResponse:
      description: A JSON array of shops
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
        text/plain:
          schema:
            type: array
            items:
              type: string
  schemas:
    Address:
      type: string
    ErrorModel:
      type: object
      required:
      - message
      - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedErrorModel:
      allOf:
      - $ref: '#/components/schemas/ErrorModel'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string
          address:
            $ref: '#/components/schemas/Address'